import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// This is good for SEO
export const metadata: Metadata = {
  title: "My Awesome App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // The required html tag
    <html lang="en">
      {/* The required body tag */}
      <body className={inter.className}>
        {/* Your page content will be injected here */}
        {children}
      </body>
    </html>
  );
}
