import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./_components/Navigation";
import Logo from "./_components/Logo";

// import "tailwindcss";

import "@/app/_styles/globals.css";

// This is good for SEO
export const metadata: Metadata = {
  title: "hotel booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-primary-100">
        <header>
          <Logo />
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
